=== topological-state/stskit/stskit/schema/config.schema3.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://github.com/topological-state/stskit/stskit/schema/config.schema.json",
    "title": "STSdispo configuration schema",
    "description": "Schema of STSdispo configuration files",
    "type": "object",
    "properties": {
        "_aid": {
            "description": "Anlage/Stellwerk ID, vom Simulator vorgegeben.",
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "_build": {
            "description": "Build number des Simulators.",
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "_name": {
            "description": "Name der Anlage/des Stellwerks, vom Simulator vorgegeben.",
            "type": "string"
        },
        "_region": {
            "description": "Name der Region, vom Simulator vorgegeben.",
            "type": "string"
        },
        "_version": {
            "description": "Versionsnummer des Konfigurationsschemas.",
            "type": "integer",
            "exclusiveMinimum": 0
        },
        "default": {
            "description": "True = Konfigurationsdaten wurden automatisch generiert.",
            "type": "boolean"
        },
        "elemente": {
            "description": "Zuordnung von Gleisen zu Betriebsstellen. Es müssen nur modifizierte Elemente (auto = false) angegeben werden. Zu jedem modifizierten Stammelement, muss jedoch mindestens ein ganzer Ast zu einem Gleis angegeben werden.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Name des Elements, Gleisnamen entsprechen denjenigen im Sim.",
                        "type": "string"
                    },
                    "sichtbar": {
                        "description": "Sichtbarkeit in Gleisbelegung. Default ist True.",
                        "type": "boolean"
                    },
                    "auto": {
                        "description": "Automatische Konfiguration. Auf False setzen, wenn der Eintrag manuell verändert wurde! Default ist True.",
                        "type": "boolean"
                    },
                    "ordnung": {
                        "description": "Sortierordnung. Default = 0",
                        "type": "integer"
                    }
                },
                "required": ["name"],
                "oneOf": [
                    {
                        "properties": {
                            "typ": {
                                "description": "Elementtyp: Gl (Gleis), Bs (Bahnsteig), Bft (Bahnhofteil), Agl (Anschlussgleis)",
                                "type": "string",
                                "enum": ["Gl", "Bs", "Bft", "Agl"]
                            },
                            "stamm": {
                                "description": "Name des uebergeordneten Elements. Kann bei Bf und Anst leer sein. ",
                                "type": "string"
                            },
                            "flags": {
                                "description": "Gleismarkierungen. Buchstaben haben folgende Bedeutung: S = Sperrung. Default ist leer.",
                                "type": "string"
                            },
                            "gleise": {
                                "description": "Anzahl der Gleise: 1 = eingleisige Ein- und Ausfahrt. Minimum 1. Default ist 1.",
                                "type": "integer",
                                "minimum": 1
                            }
                        },
                        "required": ["stamm", "typ"]
                    },
                    {
                        "properties": {
                            "typ": {
                                "description": "Elementtyp: Bf (Bahnhof), Anst (Anschlussstelle)",
                                "type": "string",
                                "enum": ["Bf", "Anst"]
                            },
                            "linienstil": {
                                "description": "Matplotlib-Linienstil des Bahnhofs im Bildfahrplan. Mögliche Werte: '-', '--', '-.', ':', '-w', '--w', '-.w', ':w', '' (keine Linie). Default ist ':'.",
                                "type": "string",
                                "enum": ["-", "--", "-.", ":", "-w", "--w", "-.w", ":w", ""]
                            }
                        },
                        "required": ["typ"]
                    }
                ]
            },
            "uniqueItems": true
        },
        "strecken": {
            "description": "Definition der Strecken für den Streckenfahrplan.",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "name": {
                        "description": "Streckenname. Frei wählbar.",
                        "type": "string"
                    },
                    "ordnung": {
                        "description": "Sortierordnung",
                        "type": "integer",
                        "minimum": 1
                    },
                    "haupt": {
                        "description": "Hauptstrecke = Voreinstellung im Streckenfahrplan. Es darf nur eine Strecke True sein.",
                        "type": "boolean"
                    },
                    "stationen": {
                        "description": "Stationsliste",
                        "type": "array",
                        "items": {
                            "description": "Station: Anschlussstelle, Bahnhof oder Bahnhofteil, im Format 'Typ Name'",
                            "type": "string"
                        },
                        "minItems": 2
                    },
                    "auto": {
                        "description": "Automatisch generiert. Auf False setzen, wenn der Eintrag manuell verändert wurde! Default ist True.",
                        "type": "boolean"
                    }
                },
                "required": ["name", "stationen"]
            },
            "uniqueItems": true
        },
        "streckenmarkierung": {
            "description": "Markierung von Streckenabschnitten",
            "type": "array",
            "items": {
                "type": "object",
                "properties": {
                    "station1": {
                        "type": "string",
                        "description": "Station: Anschlussstelle, Bahnhof oder Bahnhofteil, im Format 'Typ Name'"
                    },
                    "station2": {
                        "type": "string",
                        "description": "Station: Anschlussstelle, Bahnhof oder Bahnhofteil, im Format 'Typ Name'"
                    },
                    "fahrzeit": {
                        "type": "number",
                        "minimum": 0,
                        "maximum": 60,
                        "description": "Durschnittliche Fahrzeit in Minuten. Bestimmt die Länge des Abschnitts im Bildfahrplan. Falls Null, wird die automatisch berechnete Fahrzeit verwendet."
                    },
                    "flags": {
                        "type": "string",
                        "description": "Streckenmarkierungen: Buchstaben haben folgende Bedeutung: E = eingleisig"
                    }
                },
                "required": ["station1", "station2", "flags"]
            },
            "uniqueItems": true
        },
        "widgets": {
            "description": "Liste und Position der offenen Fenster.",
            "type": "array"

        },
        "zugschema": {
            "description": "Name des Zugschemas.",
            "type": "string"
        }
    },
    "required": ["_aid", "_build", "_version"]
}

=== topological-state/stskit/stskit/config/857.json
{
  "default": true,
  "_aid": 857,
  "_build": 5851,
  "_name": "Bolzano/Bozen",
  "_region": "Triveneto",
  "elemente": [
    {
      "name": "Bressanone",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Chiusa",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "E-A Merano",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Gbf Süd",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Laives",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Ponte",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Prato",
      "typ": "Bf",
      "auto": true,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "Bolzano",
      "typ": "Bf",
      "auto": false,
      "sichtbar": true,
      "flags": ""
    },
    {
      "name": "3",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "5",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "4",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "1",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "2",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "8",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "7",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "9",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "6",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "3",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "3G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "3",
      "gleise": 1
    },
    {
      "name": "5",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "5",
      "gleise": 1
    },
    {
      "name": "4",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "4",
      "gleise": 1
    },
    {
      "name": "4G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "4",
      "gleise": 1
    },
    {
      "name": "1",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "1",
      "gleise": 1
    },
    {
      "name": "1G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "1",
      "gleise": 1
    },
    {
      "name": "2G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "2",
      "gleise": 1
    },
    {
      "name": "8G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "8",
      "gleise": 1
    },
    {
      "name": "7G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "7",
      "gleise": 1
    },
    {
      "name": "9G",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "9",
      "gleise": 1
    },
    {
      "name": "6",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "6",
      "gleise": 1
    },
    {
      "name": "1T",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "1",
      "gleise": 1
    },
    {
      "name": "37",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "38",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "40",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "39",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "37a",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "37b",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "37",
      "gleise": 1
    },
    {
      "name": "38a",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "38",
      "gleise": 1
    },
    {
      "name": "38b",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "38",
      "gleise": 1
    },
    {
      "name": "40a",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "40",
      "gleise": 1
    },
    {
      "name": "40b",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "40",
      "gleise": 1
    },
    {
      "name": "39a",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "39",
      "gleise": 1
    },
    {
      "name": "39b",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "39",
      "gleise": 1
    },
    {
      "name": "43",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "43",
      "gleise": 1
    },
    {
      "name": "42",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "42",
      "gleise": 1
    },
    {
      "name": "41",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "41",
      "gleise": 1
    },
    {
      "name": "67",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "67",
      "gleise": 1
    },
    {
      "name": "Güter",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "Güter",
      "gleise": 1
    },
    {
      "name": "Rola 1",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "Rola 1",
      "gleise": 1
    },
    {
      "name": "61",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "61",
      "gleise": 1
    },
    {
      "name": "66",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "66",
      "gleise": 1
    },
    {
      "name": "68",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "68",
      "gleise": 1
    },
    {
      "name": "Rola 2",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "Rola 2",
      "gleise": 1
    },
    {
      "name": "65",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "65",
      "gleise": 1
    },
    {
      "name": "65",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "65",
      "gleise": 1
    },
    {
      "name": "84",
      "typ": "Bs",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "84",
      "gleise": 1
    },
    {
      "name": "84",
      "typ": "Gl",
      "auto": false,
      "sichtbar": true,
      "flags": "",
      "stamm": "84",
      "gleise": 1
    },
    {
      "name": "Bressanone 3",
      "typ": "Bft",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone"
    },
    {
      "name": "Bressanone 3",
      "typ": "Bs",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 4",
      "typ": "Bs",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 1",
      "typ": "Bs",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 2",
      "typ": "Bs",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 5",
      "typ": "Bs",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 3G",
      "typ": "Gl",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 3",
      "typ": "Gl",
      "auto": true,
      "sichtbar": true,
      "flags": "",
      "stamm": "Bressanone 3",
      "gleise": 1
    },
    {
      "name": "Bressanone 4G",
      "typ": "Gl",
      "auto": true,
      "sichtbar": true,
